### ISSUE TITLE
Idempotent repo creation

### ISSUE THREAD

**Issue by rgarrigue** [Katello/puppet-pulp#205] opened 2017-03-09 15:29 UTC
Hello

I'm ending up with an Error on a second run whenever a repository is already created.

```
==> test.vagrant.local: Error: /Stage[main]/Profiles::Pulp/Pulp_puppetrepo[puppetlabs]: Could not evaluate: Execution of '/usr/bin/pulp-admin puppet repo create --repo-id puppetlabs --display-name Forge Puppetlabs --feed http://forge.puppetlabs.com/ --validate false --verify-feed-ssl false --max-downloads 10 --serve-http true --serve-https false' returned 65: A resource with the ID "puppetlabs" already exists.
```

We've looked around a bit in api.rb, there's no existence check 

Regards,

**Comment by cristifalcas** [comment] 2017-03-09 16:06
There is no need for existence check with puppet providers.

All existing resources are created by the provider when the puppet run starts. Puppet knows about declared resources inside manifests and it decides if a resource already exists or it should be created.

The error is very strange, because from my point of view, it should not happen. 

Can you post the output from this:

    pulp-admin puppet repo list --details --repo-id puppetlabs
    puppet resource pulp_puppetrepo

And the definition from the manifest of pulp_puppetrepo[puppetlabs]

**Comment by rgarrigue** [comment] 2017-03-09 16:48
Here's my first run

```
==> test.vagrant.local: Error: Could not prefetch pulp_rpmrepo provider 'api': https request for repo "# threw exception SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed. Connection details: url=https://test.vagrant.local:443/pulp/api/v2/repositories///, cert_path=/root/.pulp/user-cert.pem.
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Pulp_rpmrepo[epel-7]/ensure: created
==> test.vagrant.local: Error: /Stage[main]/Profiles::Pulp/Pulp_rpmrepo[epel-7]: Could not evaluate: https request for repo "epel-7# threw exception SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed. Connection details: url=https://test.vagrant.local:443/pulp/api/v2/repositories/epel-7///?details=True, cert_path=/root/.pulp/user-cert.pem.
==> test.vagrant.local: Error: Could not prefetch pulp_puppetrepo provider 'api': https request for repo "# threw exception SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed. Connection details: url=https://test.vagrant.local:443/pulp/api/v2/repositories///, cert_path=/root/.pulp/user-cert.pem.
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Pulp_puppetrepo[puppetlabs]/ensure: created
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Pulp_rpmrepo[centos-7]/ensure: created
==> test.vagrant.local: Error: /Stage[main]/Profiles::Pulp/Pulp_puppetrepo[puppetlabs]: Could not evaluate: https request for repo "puppetlabs# threw exception SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed. Connection details: url=https://test.vagrant.local:443/pulp/api/v2/repositories/puppetlabs///?details=True, cert_path=/root/.pulp/user-cert.pem.
==> test.vagrant.local: Error: /Stage[main]/Profiles::Pulp/Pulp_rpmrepo[centos-7]: Could not evaluate: https request for repo "centos-7# threw exception SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed. Connection details: url=https://test.vagrant.local:443/pulp/api/v2/repositories/centos-7///?details=True, cert_path=/root/.pulp/user-cert.pem.
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Pulp_rpmrepo[centos-7-updates]/ensure: created
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Anchor[repositories]: Dependency Pulp_rpmrepo[centos-7] has failures: true
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Anchor[repositories]: Dependency Pulp_rpmrepo[centos-7-updates] has failures: true
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Anchor[repositories]: Dependency Pulp_rpmrepo[epel-7] has failures: true
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Anchor[repositories]: Dependency Pulp_puppetrepo[puppetlabs] has failures: true
==> test.vagrant.local: Error: /Stage[main]/Profiles::Pulp/Pulp_rpmrepo[centos-7-updates]: Could not evaluate: https request for repo "centos-7-updates# threw exception SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed. Connection details: url=https://test.vagrant.local:443/pulp/api/v2/repositories/centos-7-updates///?details=True, cert_path=/root/.pulp/user-cert.pem.
==> test.vagrant.local: Warning: /Stage[main]/Profiles::Pulp/Anchor[repositories]: Skipping because of failed dependencies
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Pulp_schedule[puppetlabs]: Dependency Pulp_rpmrepo[centos-7] has failures: true
==> test.vagrant.local: Error: Could not prefetch pulp_schedule provider 'api': https request for repo "# threw exception SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed. Connection details: url=https://test.vagrant.local:443/pulp/api/v2/repositories///, cert_path=/root/.pulp/user-cert.pem.
```

then here is the second one

```
==> test.vagrant.local: Notice: /Stage[main]/Pulp::Database/Exec[migrate_pulp_db]: Triggered 'refresh' from 1 events
==> test.vagrant.local: Notice: /Stage[main]/Pulp::Service/Exec[pulp refresh system service]: Triggered 'refresh' from 1 events
==> test.vagrant.local: Notice: /Stage[main]/Pulp::Service/Service[pulp_celerybeat]: Triggered 'refresh' from 1 events
==> test.vagrant.local: Notice: /Stage[main]/Pulp::Service/Service[pulp_streamer]: Triggered 'refresh' from 1 events
==> test.vagrant.local: Notice: /Stage[main]/Pulp::Service/Service[pulp_resource_manager]: Triggered 'refresh' from 1 events
==> test.vagrant.local: Notice: /Stage[main]/Pulp::Service/Service[pulp_workers]: Triggered 'refresh' from 1 events
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Pulp_rpmrepo[epel-7]/ensure: created
==> test.vagrant.local: Error: Could not prefetch pulp_rpmrepo provider 'api': https request for repo "# threw exception SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed. Connection details: url=https://test.vagrant.local:443/pulp/api/v2/repositories///, cert_path=/root/.pulp/user-cert.pem.
==> test.vagrant.local: Error: /Stage[main]/Profiles::Pulp/Pulp_rpmrepo[epel-7]: Could not evaluate: Execution of '/usr/bin/pulp-admin rpm repo create --repo-id epel-7 --display-name EPEL-7-x86_64 --feed http://download.fedoraproject.org/pub/epel/7/x86_64 --validate false --verify-feed-ssl false --remove-missing true --retain-old-count 1 --relative-url epel-7 --serve-http true --serve-https false --checksum-type sha256' returned 65: A resource with the ID "epel-7" already exists.
==> test.vagrant.local: Error: Could not prefetch pulp_puppetrepo provider 'api': https request for repo "# threw exception SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed. Connection details: url=https://test.vagrant.local:443/pulp/api/v2/repositories///, cert_path=/root/.pulp/user-cert.pem.
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Pulp_puppetrepo[puppetlabs]/ensure: created
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Pulp_rpmrepo[centos-7]/ensure: created
==> test.vagrant.local: Error: /Stage[main]/Profiles::Pulp/Pulp_puppetrepo[puppetlabs]: Could not evaluate: Execution of '/usr/bin/pulp-admin puppet repo create --repo-id puppetlabs --display-name Forge Puppetlabs --feed http://forge.puppetlabs.com/ --validate false --verify-feed-ssl false --max-downloads 10 --serve-http true --serve-https false' returned 65: A resource with the ID "puppetlabs" already exists.
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Pulp_rpmrepo[centos-7-updates]/ensure: created
==> test.vagrant.local: Error: /Stage[main]/Profiles::Pulp/Pulp_rpmrepo[centos-7]: Could not evaluate: Execution of '/usr/bin/pulp-admin rpm repo create --repo-id centos-7 --display-name CentOS-7-x86_64 --feed http://mirror.centos.org/centos/7/os/x86_64/ --validate false --remove-missing true --retain-old-count 1 --relative-url centos/7/os/x86_64/ --serve-http true --serve-https false --checksum-type sha256' returned 65: A resource with the ID "centos-7" already exists.
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Anchor[repositories]: Dependency Pulp_rpmrepo[centos-7] has failures: true
==> test.vagrant.local: Error: /Stage[main]/Profiles::Pulp/Pulp_rpmrepo[centos-7-updates]: Could not evaluate: Execution of '/usr/bin/pulp-admin rpm repo create --repo-id centos-7-updates --display-name CentOS-7-x86_64 updates --feed http://mirror.centos.org/centos/7/updates/x86_64/ --validate false --verify-feed-ssl false --remove-missing true --retain-old-count 1 --relative-url centos-7-updates --serve-http true --serve-https false --checksum-type sha256' returned 65: A resource with the ID "centos-7-updates" already exists.
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Anchor[repositories]: Dependency Pulp_rpmrepo[centos-7-updates] has failures: true
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Anchor[repositories]: Dependency Pulp_rpmrepo[epel-7] has failures: true
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Anchor[repositories]: Dependency Pulp_puppetrepo[puppetlabs] has failures: true
==> test.vagrant.local: Warning: /Stage[main]/Profiles::Pulp/Anchor[repositories]: Skipping because of failed dependencies
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Pulp_schedule[puppetlabs]: Dependency Pulp_rpmrepo[centos-7] has failures: true
==> test.vagrant.local: Error: Could not prefetch pulp_schedule provider 'api': https request for repo "# threw exception SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed. Connection details: url=https://test.vagrant.local:443/pulp/api/v2/repositories///, cert_path=/root/.pulp/user-cert.pem.
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Pulp_schedule[puppetlabs]: Dependency Pulp_rpmrepo[centos-7-updates] has failures: true
```

Here is the hiera

```
---
########## Pulp ##########
profiles::pulp::server_name: 'test.vagrant.local'
profiles::pulp::admin_login: 'l'
profiles::pulp::admin_password: 'p'
profiles::pulp::email_enabled: true
profiles::pulp::email_from: 'testpulp@home.fr'
profiles::pulp::email_host: 'smtp.home.fr'
profiles::pulp::email_port: '25'
profiles::pulp::enable_docker: true
profiles::pulp::enable_python: true
profiles::pulp::debug: true

profiles::pulp::rpmrepos:
  'centos-7':
    checksum_type: 'sha256'
    display_name: 'CentOS-7-x86_64'
    feed: 'http://mirror.centos.org/centos/7/os/x86_64/'
    # relative_url: 'centos/7/os/x86_64/'
    remove_missing: true
    retain_old_count: '1'
    serve_http: true
    serve_https: false
    validate: false
    verify_feed_ssl: false

  'centos-7-updates':
    checksum_type: 'sha256'
    display_name: 'CentOS-7-x86_64 updates'
    feed: 'http://mirror.centos.org/centos/7/updates/x86_64/'
    remove_missing: true
    retain_old_count: '1'
    serve_http: true
    serve_https: false
    validate: false
    verify_feed_ssl: false
    
  'epel-7':
    checksum_type: 'sha256'
    display_name: 'EPEL-7-x86_64'
    feed: 'http://download.fedoraproject.org/pub/epel/7/x86_64'
    remove_missing: true
    retain_old_count: '1'
    serve_http: true
    serve_https: false
    validate: false
    verify_feed_ssl: false

profiles::pulp::puppetrepos:
  'puppetlabs':
    display_name: 'Forge Puppetlabs'
    feed: 'http://forge.puppetlabs.com/'
    max_downloads: '10'
    serve_http: true
    serve_https: false
    validate: false
    verify_feed_ssl: false
```

The puppet repo details

```
[root@test pulp]# pulp-admin puppet repo list --details --repo-id puppetlabs
+----------------------------------------------------------------------+
                          Puppet Repositories
+----------------------------------------------------------------------+

Id:                   puppetlabs
Display Name:         Forge Puppetlabs
Description:          None
Content Unit Counts:  
Notes:                
Scratchpad:           
Importers:            
  Config:               
    Feed:           http://forge.puppetlabs.com/
    Max Downloads:  10
    SSL Validation: False
    Validate:       False
  Id:                   puppet_importer
  Importer Type Id:     puppet_importer
  Last Override Config: 
  Last Sync:            None
  Last Updated:         2017-03-09T16:38:18Z
  Repo Id:              puppetlabs
  Scratchpad:           None
Distributors:         
  Auto Publish:         True
  Config:               
    Serve Http:  True
    Serve Https: False
  Distributor Type Id:  puppet_distributor
  Id:                   puppet_distributor
  Last Override Config: 
  Last Publish:         None
  Last Updated:         2017-03-09T16:38:18Z
  Repo Id:              puppetlabs
  Scratchpad:    
```

The puppet ressource return can't find ressource, I miss time today to find out the exact relevant command in the box, but you got most of the parameters in the second run output since it's giving the full failed command

**Comment by cristifalcas** [comment] 2017-03-09 17:33
The issue is because of " Error: Could not prefetch pulp_rpmrepo provider 'api': ". It doesn't want to connect to the api due to ssl issues, so it can't gather existing resources. Because of this, it thinks that the resources from hiera don't exist and tries to create them again.

Could you add the certificate from the pulp server to the system ones? Copy the ca.pem to /etc/pki/ca-trust/source/anchors/pulp_ca.pem and execute:

    /usr/bin/update-ca-trust enable
    /usr/bin/update-ca-trust extract

Maybe the provider should not check the ssl for the pulp server? I'm not sure that this can be parameterized.

**Comment by rgarrigue** [comment] 2017-03-10 09:07
So, I remade the vm with the same log as first run above. 

Then I connected and

```
[root@test pulp]# cp /etc/pki/pulp/ca.crt /etc/pki/ca-trust/source/anchors/pulp_ca.pem
[root@test pulp]# update-ca-trust enable
[root@test pulp]# update-ca-trust extract
```

Then exit and vagrant provision again

```
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Pulp_rpmrepo[epel-7]/ensure: created
==> test.vagrant.local: Error: Could not prefetch pulp_rpmrepo provider 'api': undefined method `each' for nil:NilClass
==> test.vagrant.local: Error: /Stage[main]/Profiles::Pulp/Pulp_rpmrepo[epel-7]: Could not evaluate: Execution of '/usr/bin/pulp-admin rpm repo create --repo-id epel-7 --display-name EPEL-7-x86_64 --feed http://download.fedoraproject.org/pub/epel/7/x86_64 --validate false --verify-feed-ssl false --remove-missing true --retain-old-count 1 --relative-url epel-7 --serve-http true --serve-https true --checksum-type sha256' returned 65: A resource with the ID "epel-7" already exists.
==> test.vagrant.local: Error: Could not prefetch pulp_puppetrepo provider 'api': undefined method `each' for nil:NilClass
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Pulp_puppetrepo[puppetlabs]/ensure: created
==> test.vagrant.local: Error: /Stage[main]/Profiles::Pulp/Pulp_puppetrepo[puppetlabs]: Could not evaluate: Execution of '/usr/bin/pulp-admin puppet repo create --repo-id puppetlabs --display-name Forge Puppetlabs --feed http://forge.puppetlabs.com/ --validate false --verify-feed-ssl false --max-downloads 10 --serve-http true --serve-https true' returned 65: A resource with the ID "puppetlabs" already exists.
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Pulp_rpmrepo[centos-7]/ensure: created
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Pulp_rpmrepo[centos-7-updates]/ensure: created
==> test.vagrant.local: Error: /Stage[main]/Profiles::Pulp/Pulp_rpmrepo[centos-7]: Could not evaluate: Execution of '/usr/bin/pulp-admin rpm repo create --repo-id centos-7 --display-name CentOS-7-x86_64 --feed http://mirror.centos.org/centos/7/os/x86_64/ --validate false --verify-feed-ssl false --remove-missing true --retain-old-count 1 --relative-url centos-7 --serve-http true --serve-https true --checksum-type sha256' returned 65: A resource with the ID "centos-7" already exists.
==> test.vagrant.local: Error: /Stage[main]/Profiles::Pulp/Pulp_rpmrepo[centos-7-updates]: Could not evaluate: Execution of '/usr/bin/pulp-admin rpm repo create --repo-id centos-7-updates --display-name CentOS-7-x86_64 updates --feed http://mirror.centos.org/centos/7/updates/x86_64/ --validate false --verify-feed-ssl false --remove-missing true --retain-old-count 1 --relative-url centos-7-updates --serve-http true --serve-https true --checksum-type sha256' returned 65: A resource with the ID "centos-7-updates" already exists.
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Anchor[repositories]: Dependency Pulp_rpmrepo[centos-7] has failures: true
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Anchor[repositories]: Dependency Pulp_rpmrepo[centos-7-updates] has failures: true
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Anchor[repositories]: Dependency Pulp_rpmrepo[epel-7] has failures: true
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Anchor[repositories]: Dependency Pulp_puppetrepo[puppetlabs] has failures: true
==> test.vagrant.local: Warning: /Stage[main]/Profiles::Pulp/Anchor[repositories]: Skipping because of failed dependencies
==> test.vagrant.local: Error: Could not prefetch pulp_schedule provider 'api': undefined method `each' for nil:NilClass
```

I removed manually the existing before provisioning again

```
==> test.vagrant.local: Error: Could not prefetch pulp_rpmrepo provider 'api': undefined method `each' for nil:NilClass
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Pulp_rpmrepo[epel-7]/ensure: created
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Pulp_puppetrepo[puppetlabs]/ensure: created
==> test.vagrant.local: Error: Could not prefetch pulp_puppetrepo provider 'api': undefined method `each' for nil:NilClass
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Pulp_rpmrepo[centos-7]/ensure: created
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Pulp_rpmrepo[centos-7-updates]/ensure: created
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Pulp_schedule[puppetlabs]/ensure: created
==> test.vagrant.local: Error: Could not prefetch pulp_schedule provider 'api': undefined method `each' for nil:NilClass
==> test.vagrant.local: Error: /Stage[main]/Profiles::Pulp/Pulp_schedule[puppetlabs]: Could not evaluate: undefined method `[]' for nil:NilClass
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Pulp_schedule[centos-7-updates]/ensure: created
==> test.vagrant.local: Error: /Stage[main]/Profiles::Pulp/Pulp_schedule[centos-7-updates]: Could not evaluate: undefined method `[]' for nil:NilClass
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Pulp_schedule[epel-7]/ensure: created
==> test.vagrant.local: Notice: /Stage[main]/Profiles::Pulp/Pulp_schedule[centos-7]/ensure: created
==> test.vagrant.local: Error: /Stage[main]/Profiles::Pulp/Pulp_schedule[epel-7]: Could not evaluate: undefined method `[]' for nil:NilClass
==> test.vagrant.local: Error: /Stage[main]/Profiles::Pulp/Pulp_schedule[centos-7]: Could not evaluate: undefined method `[]' for nil:NilClass
```

Sadly, I've no schedule created. But I can create it with cli.

```
[root@test vagrant]# pulp-admin rpm repo sync schedules list --repo-id centos-7
+----------------------------------------------------------------------+
                               Schedules
+----------------------------------------------------------------------+

There are no schedules defined for this operation.

[root@test vagrant]# pulp-admin rpm repo sync schedules create --repo-id centos-7 -s 2017-01-01T22:12:34Z/P1D
Schedule successfully created

[root@test vagrant]# pulp-admin rpm repo sync schedules list --repo-id centos-7
+----------------------------------------------------------------------+
                               Schedules
+----------------------------------------------------------------------+

Schedule: 2017-01-01T22:12:34Z/P1D
Id:       58c26c136febe714f6cbf1da
Enabled:  True
Next Run: 2017-03-10T22:12:34Z
```

I agree that I wish I could avoid the ssl part for my standalone pulp server. But as long as I got a workaround... I'm gonna add an exec with the cp pem / update-ca.

**Comment by cristifalcas** [comment] 2017-03-10 10:37
You still have errors that should not appear.

Can you tell me if the following command returns valid output:

    curl --cert /root/.pulp/user-cert.pem https://$(hostname):443/pulp/api/v2/repositories/

**Comment by horacer** [comment] 2017-05-03 14:06
Hi! I am running into the same problem right now. I have to use a specific cert for apache for my organization. So I set the following variables accordingly:

https_cert
https_key
https_chain
ca_cert

I do not have access to the CA key. So I'm trying to figure out how to make the puppet run working.

Here's the output of the curl command:
[root@pulp ~]# curl --cert /root/.pulp/user-cert.pem https://$(hostname):443/pulp/api/v2/repositories/
curl: (60) Peer's certificate issuer has been marked as not trusted by the user.

I already tried the update-ca-trust part.

**Comment by ekohl** [comment] 2017-05-21 15:42
@horacer and if you add ```--cacert <path_to_cacert.pem>``` to the curl command, does that work?

**Comment by horacer** [comment] 2017-05-22 11:20
@ekohl thanks for writing in. it turned out, I somehow failed in trusting our custom ca cert for apache using update-ca-trust. That was the culprit but I can't recall what I was doing wrong... All I'm doing now is running an exec resource in my puppet manifest:

cp ${global_ca} /etc/pki/ca-trust/source/anchors/ && update-ca-trust enable && update-ca-trust extract

And voila ;)

**Comment by ekohl** [comment] 2017-05-28 19:18
Isn't a much easier solution to set ```$pulp::admin::ca_path``` to ```/etc/pki/pulp/ca.crt```? I'm trying to write some integration tests to verify this.

**Comment by ekohl** [comment] 2017-05-28 19:53
https://github.com/Katello/puppet-pulp/pull/248 is a WIP to fix this. It still need the proper autorequires so the providers are correctly chained and idempotency is guaranteed.

**Closed** 2017-07-12 20:22 UTC
