### ISSUE TITLE
EPEL Dependency

### ISSUE THREAD

**Issue by TJM** [Katello/puppet-pulp#247] opened 2017-05-26 00:29 UTC
It seems that some parts of this code (mongo) are dependent on EPEL. You have "worked around" this in your tests: https://github.com/Katello/puppet-pulp/blob/9241c27dab154eae587d1a68edf3082e966399a3/spec/spec_helper_acceptance.rb#L24-L25

```
        # We always need EPEL
        on host, puppet('resource', 'package', 'epel-release', 'ensure=installed')
```

However, I believe it should be spelled out in puppet code, either as a package resource or "include ::epel" with the requisite "$manage_epel_repo" attributes to disable the behavior.

~tommy

**Comment by ekohl** [comment] 2017-05-26 13:55
This is a duplicate of https://github.com/Katello/puppet-pulp/issues/164

**Closed by ekohl** 2017-05-26 13:55 UTC

**Comment by TJM** [comment] 2017-05-27 00:48
Sorry! I swear I looked and didn't see it, perhaps searching "this repository" doesn't search issues :)
